"""Email notification system for new matching grants."""

from __future__ import annotations

import os
import smtplib
from datetime import datetime
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from typing import Optional

from au_grants_agent.config import settings
from au_grants_agent.database import Database
from au_grants_agent.proposal.matcher import rank_grants
from au_grants_agent.proposal.profiles import list_profiles, load_profile
from au_grants_agent.utils.logger import get_logger

logger = get_logger()


def _get_smtp_config() -> dict:
    """Load SMTP settings from environment."""
    return {
        "host": os.getenv("SMTP_HOST", "smtp.gmail.com"),
        "port": int(os.getenv("SMTP_PORT", "587")),
        "user": os.getenv("SMTP_USER", ""),
        "password": os.getenv("SMTP_PASSWORD", ""),
        "from_email": os.getenv("NOTIFY_FROM", os.getenv("SMTP_USER", "")),
        "to_email": os.getenv("NOTIFY_TO", ""),
        "use_tls": os.getenv("SMTP_TLS", "true").lower() == "true",
    }


def _build_html_digest(profile_name: str, matches: list) -> str:
    """Build an HTML email digest of matching grants."""
    now = datetime.utcnow().strftime("%d %b %Y")
    rows = ""
    for m in matches:
        g = m.grant
        score_pct = f"{m.score:.0%}"
        reasons = "<br>".join(m.reasons[:3]) if m.reasons else "-"
        closing = g.closing_date or "N/A"
        url = g.source_url or "#"
        amount = ""
        if g.amount_min:
            amount = f"${g.amount_min:,.0f}"
            if g.amount_max and g.amount_max != g.amount_min:
                amount += f" - ${g.amount_max:,.0f}"

        rows += f"""
        <tr>
            <td style="padding:8px;border-bottom:1px solid #ddd">
                <a href="{url}" style="color:#00aa66;font-weight:bold">{g.title[:80]}</a>
                <br><small style="color:#666">{g.agency or ''} | {g.category or ''}</small>
            </td>
            <td style="padding:8px;border-bottom:1px solid #ddd;text-align:center">
                <span style="background:#{'00aa66' if m.score >= 0.5 else 'cc8800'};color:white;
                padding:2px 8px;border-radius:4px">{score_pct} {m.rating}</span>
            </td>
            <td style="padding:8px;border-bottom:1px solid #ddd">{amount}</td>
            <td style="padding:8px;border-bottom:1px solid #ddd">{closing}</td>
            <td style="padding:8px;border-bottom:1px solid #ddd;font-size:12px">{reasons}</td>
        </tr>"""

    return f"""
    <html>
    <body style="font-family:Arial,sans-serif;max-width:900px;margin:0 auto">
        <div style="background:#00aa66;color:white;padding:20px;border-radius:8px 8px 0 0">
            <h1 style="margin:0">AU Grants Agent</h1>
            <p style="margin:4px 0 0 0">Grant Matching Digest — {now}</p>
        </div>
        <div style="padding:20px;background:#f9f9f9;border:1px solid #ddd;border-top:none">
            <p><strong>Profile:</strong> {profile_name}</p>
            <p><strong>Matching grants found:</strong> {len(matches)}</p>
            <table style="width:100%;border-collapse:collapse;margin-top:16px">
                <tr style="background:#eee">
                    <th style="padding:8px;text-align:left">Grant</th>
                    <th style="padding:8px">Score</th>
                    <th style="padding:8px">Amount</th>
                    <th style="padding:8px">Closing</th>
                    <th style="padding:8px">Why</th>
                </tr>
                {rows}
            </table>
            <p style="margin-top:20px;color:#666;font-size:12px">
                Generated by AU Grants Agent | <a href="https://nullshift.sh">NullShift</a>
            </p>
        </div>
    </body>
    </html>
    """


def send_email(subject: str, html_body: str) -> bool:
    """Send an email via SMTP."""
    cfg = _get_smtp_config()

    if not cfg["user"] or not cfg["to_email"]:
        logger.warning("SMTP not configured — set SMTP_USER, SMTP_PASSWORD, NOTIFY_TO in .env")
        return False

    msg = MIMEMultipart("alternative")
    msg["Subject"] = subject
    msg["From"] = cfg["from_email"]
    msg["To"] = cfg["to_email"]
    msg.attach(MIMEText(html_body, "html"))

    try:
        with smtplib.SMTP(cfg["host"], cfg["port"]) as server:
            if cfg["use_tls"]:
                server.starttls()
            server.login(cfg["user"], cfg["password"])
            server.send_message(msg)
        logger.info("Email sent to %s", cfg["to_email"])
        return True
    except Exception as e:
        logger.error("Failed to send email: %s", e)
        return False


def send_digest(
    profile_name: Optional[str] = None,
    min_score: float = 0.3,
    top_n: int = 20,
) -> bool:
    """Find matching grants and send an email digest.

    Args:
        profile_name: Org profile to match against. If None, uses first available.
        min_score: Minimum match score.
        top_n: Max number of grants in digest.
    """
    # Load profile
    if not profile_name:
        profiles = list_profiles()
        if not profiles:
            logger.warning("No profiles found. Create one with 'au-grants profile create'.")
            return False
        profile_name = profiles[0][0].replace(".yaml", "")

    try:
        profile = load_profile(profile_name)
    except FileNotFoundError:
        logger.error("Profile '%s' not found.", profile_name)
        return False

    # Get grants and match
    db = Database()
    grants = db.list_grants(status="open")
    if not grants:
        logger.info("No open grants to match.")
        return False

    matches = rank_grants(grants, profile, min_score=min_score, top_n=top_n)
    if not matches:
        logger.info("No grants match above %.0f%% threshold.", min_score * 100)
        return False

    # Build and send digest
    html = _build_html_digest(profile.name, matches)
    subject = f"AU Grants Digest: {len(matches)} matching grants — {datetime.utcnow().strftime('%d %b %Y')}"
    return send_email(subject, html)
